/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.twidgetpackage;

import java.util.logging.Level;
import java.util.logging.Logger;
import twitter4j.ResponseList;
import twitter4j.Status;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.auth.AccessToken;
import twitter4j.auth.RequestToken;
import twitter4j.*;

/**
 *
 * @author Lee
 */
public class TwidgetGUI extends javax.swing.JFrame {

    
    /**
     * Creates new form TwidgetGUI
     */
    public TwidgetGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(385, 360));

        jLabel1.setText("User Name:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/twidgetpackage/resources/twitter-logo-small1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Twidget: A Test Twitter Client");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel5.setText("by Lee Synkowski");

        jLabel6.setText("Log on to:");

        jButton1.setText("Log On");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jTextField1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //look to see if we have that user in our storage
        if (df.findName(jTextField1.getText())){
            //we do have that user
            //use the stored oath passwords to log on
            String[] credentials = df.getCredentials(jTextField1.getText());
            AccessToken oathAccessToken = new AccessToken(credentials[0],credentials[1]);
            finalwindow.twitter.setOAuthAccessToken(oathAccessToken);
            
            //enter the twitter gui
            try {
                //gotta figure out if this is the right status we want
                Status currentStatus = finalwindow.twitter.showStatus(0);
                finalwindow.setStatus(currentStatus.getText());
            } catch (TwitterException ex) {
                Logger.getLogger(TwidgetGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            finalwindow.setVisible(true);


            //return to initial log in screen on close
            //this.setVisible(true);
        } else { 
            //we don't have that user, so we need to get them to verify the app with their account
            String displayURLMessage = "";
            RequestToken requestToken = new RequestToken("","");
            try {
                requestToken = finalwindow.twitter.getOAuthRequestToken();
                displayURLMessage = "" + requestToken.getAuthorizationURL();
            } catch (TwitterException ex) {
                Logger.getLogger(TwidgetGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            pe.setMessage(displayURLMessage);
            //enter the pin entry dialog window
            pe.setVisible(true);
            //use the pin to get the oauth credentials
            
            AccessToken accessToken = null; 
            try {   
            accessToken = finalwindow.twitter.getOAuthAccessToken(requestToken,pe.getPIN());
            } catch (TwitterException ex){
                Logger.getLogger(TwidgetGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            //store the oauth credentials
            df.storeaccessTokens(this.jTextField1.getText(),accessToken.getToken(),accessToken.getTokenSecret());
            
            //use the oauth credentials to log into the twitter account
            finalwindow.twitter.setOAuthAccessToken(accessToken);
            
            //enter into the final window
            this.setVisible(false);
            finalwindow.setVisible(true);
            
            //could add a way to quit back to the main window
            
            //this.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwidgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwidgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwidgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwidgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                finalwindow.twitter.setOAuthConsumer(CONSUMER_KEY, CONSUMER_KEY_SECRET);
                new TwidgetGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    //Application Keys Required to interact with Twitter
    private final static String CONSUMER_KEY ="FpE0pAD2wS7BSIpQoUBR8w";
    private final static String CONSUMER_KEY_SECRET = "FOwi4Vv9Q7fPh1vBdtyKbJN9eMrMebVD1SK2PGxQ";

    //Class instance variables
    private DataFinder df = new DataFinder();
    private PinEntry pe  = new PinEntry(this,true);
    private static TwitterGUI finalwindow = new TwitterGUI();
}
